version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
  runner-test:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - run: echo "Hello"

  runner-test:
    machine: true
    resource_class: yaseen-techlogix-namespace/yaseen
    steps:
      - run: echo "Hi I'm on Runners!"

workflows:
  testing:
    jobs:
      - runner-test
      - build